language: python
sudo: false
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls
script: python setup.py nosetests --with-coverage --cover-package=thrift_tools
after_success:
  coveralls
